---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud-nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nextcloud-nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx-nextcloud.conf
                path: nextcloud.conf
