# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  # Base image
  config.vm.box = "ubuntu/bionic64"

  # Provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1

  # Network setting
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.network :forwarded_port, guest: 6379, host: 6379
  end
  # Shell file installation
  config.vm.provision "shell", path: "bootstrap.sh"

end
