#!/usr/bin/env python3.6

import subprocess


#Command 1

def uname_funct():
    uname = "uname"
    unameArg = "-a"
    print(f"Gathering system information with {uname} command")
    subprocess.call([uname, unameArg])

#Command 2
def disk_func():
    diskspace = "df"
    diskspaceArg = "-hT"
    print(f"Gathering diskspace information with {diskspace} command")
    subprocess.call([diskspace, diskspaceArg])

# Main fucntion that call other functions
def main():
    uname_funct()
    disk_func()

main()
