---
# Run with ansible-playbook <filename> -K
# (make sure to add the IPs of machines you want to manage to /etc/ansible/hosts first)

- hosts: secondary
  gather_facts: false
  tasks:

  - name: Installing Chronyd
    yum: name=chrony state=present 

  - name: allow ntp through firewall
    shell: firewall-cmd --add-service=ntp --permanent

  - name: firewall reload
    shell: firewall-cmd --reload

  - name: Make sure Chrony is started up
    service: name=chronyd state=started enabled=yes
    tags: chrony

 
  handlers:
  - name: restart chronyd
    service: name=chronyd state=restarted
