---
# tasks file for installKVM
- name: Installing KVM Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - qemu-kvm
    - libvirt
    - libvirt-python
    - libguestfs-tools
    - virt-install

- name: Enable and Start libvirtd
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Verify KVM module is loaded
  shell: "lsmod | grep -i kvm"
  register: result
  failed_when: "result.rc != 0"